#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank.Request
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Db_Tank")]
	public partial class SQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Db_TankConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Account_Register")]
		public int SP_Account_Register([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(200)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="VarChar(200)")] string passWord, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NickName", DbType="VarChar(50)")] string nickName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(250)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sex", DbType="Bit")] System.Nullable<bool> sex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Money", DbType="Int")] System.Nullable<int> money, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gold", DbType="Int")] System.Nullable<int> gold, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiftToken", DbType="Int")] System.Nullable<int> giftToken, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Salt", DbType="VarChar(5)")] string salt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passWord, nickName, email, sex, money, gold, giftToken, salt);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
